dist: trusty
sudo: required

language: node_js
node_js:
  - "stable"
addons:
  sonarcloud:
    organization: "tanujamedisetti87-github"
    token:
      secure: "c31adcd738465686855224f7f9b30c8ec5008271"
  sauce_connect:
    username: "TanujaMedisetti87"
    access_key: "130dda79-1dea-45cd-849c-24cfbe048884"
    
script:
  - sonar-scanner
  
deploy:
  - provider: codedeploy
    access_key_id: 
      secure: "ut2sBWRpR+hHEfU295ZrK2g5VrE9I8ZTx/aSZzsKEv0068wHGdUe+GggMisrqI02JQ9aE19ag86WMPuDvakH+Lc3KUODu+9f8dorfsDCBdb1dw32IzNMWIsrdpvpa6Z4UBV3ZthUJL4waL4YmX+tfX+49NGmXQrrE3wzIwSIQ2Jlci9NvQEj7oypTSAMFMyxUmkGxKQzVVPt2WJKX6nqRUQYrxaT0NIPhQmmPPwUEQQYvdWX3RtFSE0dOsdoXI1vjoSMzyA/uZwweTq9EsGSSgkAzy1w4Gu+9CRzJNbtos9B9DMYbID18jMYxhP2lWFLbKUM0FT6QZ4lToS/Pim1bdLF5IMBnni8xt2gsFcBRUURULrHaJXN2k0oJqNludOEbiXSUVCSPJGTqnsjvdi//nmbd6bR/zKzFlyVedncR0oHhlEbhmrjKDH+19b0aYatj9MBYrZqNkosas+uronEBAAhlZtwI7C+x7oJt897sOk7KMZJ/C1MAxXcQGWlLNJsQBZaxfDlLonaLPvBxj/5LQp5pGSEP/FAJ8xqmJ7PP4o0dRMFsISuV5Wow4Uq+Ai3AmphV1AXdRKJIwEq8b3sTl/Fdvg0kzRLeDZ5MsEaOAimBKPQdU0kZ+YkBH+tam7WTy3CX4h1b6KtU4vETvnW+ZjkeaWYeNFSCQw2iT2Qr6A="
    secret_access_key:  
      secure: "rXQsNncujjYYJLl0S+lUtTB7hmmmFpSrR/f/ZDB6NghjZb/TuLxthC0ks1r0Q4Q+wVTTD26V1bNYL9xjRsHFGL2ufz6LYfTvdvxPaRAQ8nVZINQv6y3VJAx0ZCtgM3cmDAUvVaFHyy/rFRIiIcS5CxYkylXrPT/mXtkw3G/AXTfNjOVDuRUgTDPUeFcfjvVohNYvACbeErbl4K8fsgWwwiWM1zVJ80zM6NC/B/7JCQZZIMvFwTuxkAwMs2JjDeCWgzV63EW5G0NpeVnKptPI6ppbEwINY/reGNiFpMoU1oFr2BR1AIcvdFxZ8OZAsNKxa+tsrThJFY5Niwdi347gjrqeWnqzdY9EvHC5x484WZSiLFVpBdwG/HO23q2vGCZlGmAhoESyYPuCOOeOy07mxnqSJq51aDeBxB60WJ5t9EWB83Aid+sJUhcwX4eQ5aF2pXIVtoOPAH5kEk4aocBAcBYwwMlee4GaZuCTE+Age9Wf09Z4+hGnMH0030fdaeP8H655+9y0UM9odkj1OqPyfpAPHI7z4zu1ZQa37kqFLZ5EAXaZTAbEbPTX0A2G5eRPRs2IHZb1ibhICCzdm+LHNFADZUCeOXGd3R5r9C907F4y/MtVcrsGrZzvTG7u8CjyBvL3/KsPj+PHuw0rHuHZRkDwi+QTteOew+ZJSMiGkUc="
    application: Resume
    deployment_group: ResumeGroup
    
    
    
    
    
    
    
    
    
    
    
