dist: trusty
sudo: required

language: node_js
node_js:
  - "stable"
addons:
  sonarcloud:
    organization: "tanujamedisetti87-github"
    token:
      secure: "c31adcd738465686855224f7f9b30c8ec5008271"
  sauce_connect:
    username: "TanujaMedisetti87"
    access_key: "130dda79-1dea-45cd-849c-24cfbe048884"
    
script:
  - sonar-scanner
  
deploy:
  - provider: codedeploy
    access_key_id: 
      secure: "s6le5T6VdVeQTwiqhgjZM92Izla2kNFzm8rfPVCUsYPpGoDAFmwwmihnLxPK2WiDHXlF8oUoTa93TwwE9YqjvMo8/Q2XLyYaBs8nT4JlF7z7mBjglN0Wh2QbEdiMfjQfKwWsGSoFSpMTgm/oE7qurYhn/F/dNe+9VNSG1dChiz19XHgPaLaLbFrBd4QRID3CE8eLSwg8AUGqauDOold2G7rt6siyMgAxi6f9fZURFP50wBZlqFaRtO3qwythyHtNtU7TdgvNXaGfpGQG7JMDgxChQ3CgyfCBYxbXlHLBc+lDMX7e43KTVGia/6y9mqMLfIoM87VPmbXkdnWaNAMKxZWH2pwBMCR8XZnGEZ8Gqd0cNR6DJ+Zz8xLbaGLBiG199J5OQuVjUuxv6ZWMROFMXb2uJbKWP02bYW5kXpheSXoEQo/J2/p6XsKvTTjjQuyTL4ovsdq5mT9SbMdnszlj561sgpHDCpArj5fX1db3pj4xLWiA3zGXcMIFI/ua3tbEShCuO/vnJK/ZQtRKMxiRtAqnZ1ZfBM7F2BFGxgwHPXEfO0FpmKzeEtf6D07AUtbUlt1it1F3tGOh+Jslrf6cy5qJxheHhhkJJx8cr30kmX8KpcOhAt0lwt5tT+XsE65dGMUFTAp424lsxUplKCTWGhiIkjT2wKfVGuGJi52Txok="
    secret_access_key: 
      secure: "y3+yv4SoKkav3rGxtKSefZHSl2kjpdh4tY7SBEbaMgGiRQwn/HK+YNH6VlqC699/dFwntHhZpm/w79TBU9Tm07+jqy8jiNcDB5jZ2fblKMrXTe0+1NQsYbQ22AAbe7L76vfC3/HxrkYJGH7ZA/flBBjR5+v0P1d4FKLdHvgVwMQhZtfUrcLbpu5nfOvd+ekKkKa/QafY70a00ddty+GaulX/BpevKhqnrXt4BAH1EatTSlzTXbQQ030ouIWiQ/R0hYe9hAI/yB0f1Nyith8XufvMfa2aXFVWxughSPWxMOAFEpJUst0iOtblLM13mGjSIzuY39cagNE0LnMmoEPMfpmB6y+4yeL2hJxsY2hsYodlsziimAU/ATawBMVZ/X4Jn3wtEA4iH8e8TAtQWQit41xJ/qtT9285Da1vulAa9Vg0MI6bGrLipYPKZ/sNZ0s64gQW8isoMzROvzhJ4QF7LShuicVp9QKALdCMd40JKYnRfPzZUZhV9rrgiNNbI3T1ecR1A8HuxJ3aofn1x1utk116ph9x1jPEIHHACkIi0MIjMCyq0ywot94LMAZtt2C6E5E77Ol+e/cIO3Q6QdeGi7dHE60lsVaag7U5oJdJIuDaMZZyJT8dcTDaQnBuNTDYq/hNAoF6XCM/D68BDgBG0IzEqx7rdl/uqzT82vCwx/o="
 





  
  
  
