dist: trusty
sudo: required

language: node_js
node_js:
  - "stable"
addons:
  sonarcloud:
    organization: "tanujamedisetti87-github"
    token:
      secure: "c31adcd738465686855224f7f9b30c8ec5008271"
  sauce_connect:
    username: "TanujaMedisetti87"
    access_key: "130dda79-1dea-45cd-849c-24cfbe048884"
    
script:
  - sonar-scanner
  
deploy:
  - provider: codedeploy
    access_key_id:  
      secure: "POL30S7EXXq+zEdzo6DYfjUv9R0Usgl91A5QaTbPyzfIgw7ex5Fy5726SONfOuLCcdqG29vSVnh7S8nugGUArglHN+IwCAyuetSpf6WJP4A7IL20TKgH54hNXxWwZawqyGWSKFt20m4WupRDddn8Yz+Fsjcf5w52KoKLdAY9+ZDPbEeYOHOy4y1uh30HhfLoKEOHmzWcVJTd/1BIeqasCBa77izZuhs1SziOwfgDwkVD/TTgfjQalWzDKZvyYV/9PJoJgJiJpVnW0VPfD0B6ZWOhbzNz6qiLXuMzX2r358/KoGcubmHvkd1uFmu15JEB8dMXnEg873Qi7F6cVzGrnrYtx1SkPdmTIg4y6jKjwT9fLdgKr6dwpMyPotqHLmvXSQb8woY49lIDfmXdettyTruUr8Od/WLYKMoGmXkor5a+DP3EmWvzRLHiE8QjgMlxiqQnkmzypRC5zuSSHguyWrGJ157PQ/rK/GOTdFXcERmlo0HQepTuay43vXvvzN963p/kudO5KMVLtoFAR+S8l1l0X13DlMMX79FXKm6djnqzC01VROr1ZW8QG/W9LK4YQAXm1K7g8aDsmEHihsIq9a9AepRjtbZmyHm0n+FGnZV14JYHY7gO92yyx4Ln8jeraN7FI3asiiTVJsmax8a0OQry4g5pPf6rwex8CnlwEbo="
    secret_access_key: 
       secure: "tmKIdHu8hCI1pTDDx6d3EQjq0kmekm0cSUGKuQoj7H15WIZVvbKL9goB81wyuS6jo4xMjoDF7aTfzIIZLxuj+SOxK/IVWPY5BQty3siV3gFZ+DO8RFSEVN1c0oynkNty6h0uzYT6+EsADeihIVMb5kUwm0sN0ilsmp65Ed7ttg0VCP7raHEkbuBJ8rMJSQDEciyQzZp6jM1oKmxE65YtFYulq3WNuWZEi2ZO2tTgeWvwBweEg8JDiRp0cMGuNsH1uY11HWzzezhmbMhYtS+Kmb/DOc71VlGDhO9JLCq7BDiiHaSgR1/4/ccLw+vgLXica8nu03c8ihtnENTYCpfjm2MtqRjRhS7SZFP+OyT8fInYsdEaLwIzI4J0uOEDnfTQijyIzA8YlHrLBK4huLltkBsEWOdNpWaXtdJq3XERAy93zv2jJxumTkbbPWfUlb1SLgMpR+klevi5BmuV+tvBDilqxg3mhQpZWOh0Eln7UAfyXg/JN5U74TUX3EDSsMb+BLgmm8w9IbrDilQocneH8/UpIqqmfZjzK/11X1skLg86vHdyPYYBu/N7k6zvVG72sKLT+x/naJuXsgv9XmiGQHuYZtaytCsUqOdqEfMRP434WIlBh1RD7m3ZFC3HBxOFmPUp2KDrWwGAYsX73IAn1LLRFD0fgueKpKItk2HZzzc="
    application: Resume
    deployment_group: ResumeGroup
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
