dist: trusty
sudo: required

language: node_js
node_js:
  - "stable"
addons:
  sonarcloud:
    organization: "tanujamedisetti87-github"
    token:
      secure: "c31adcd738465686855224f7f9b30c8ec5008271"
  sauce_connect:
    username: "TanujaMedisetti87"
    access_key: "130dda79-1dea-45cd-849c-24cfbe048884"
    
script:
  - sonar-scanner

deploy:
  - provider: codedeploy
  access_key_id: 
    secure: "ruNtw/DpPeRJs29puj3tAXEO2KO5KWvQm0T5kVOTsIJ3agu1A2VNptdoWWrqQMV886KVahYXyyNTfvz6AU01WAqnTrbQgQp1GNmQhyyzujX71PS9qaLxNs4nWf2NDzjCneeQLDdLrxX2tB2I43in3VjJd0TgjKAzpqDhgnCn4SqHV0k0J9Qsx41P9aGMg9DvDIjHC2cncDJqrdpZwROnu3daNFGX62QpI8MukszL1AlAC1KzmDj+oOX8c3SxLNNC4jdQXcawF5gBRACxFc294EVQEwg8bsHBlTSe/EgIwcy1iwRPda3/YMF7bz7+hJQpkcn9TheVK8xK8jxkh1MS4d7Gjc9etMkaTR5ug6pJRPQYScyH6cg6KdCmviJtIKUddbkZ4/Pk5FGqBSd1G8/MMpr0tJ7UGszuE1nSrUael56EpvOrJBvGFTTypJkc46mZn6iHcEIjX3VHo6tzYyvBg9HuuqpMfx8jR8ioUtvYKycaiSxQd7jwW31BHN7hIA5XciCichXQ5/tlPJ+2EbjGhvLEiZDOLt0L9gnwQC85E0m+7r+3q2no0CgzZ75bEpjiNqhAdvBhX0yeCd6ea9T6aw1LmW+MWFs/C2s81h3wwYB0f7Nh0CxXbmkiILehl5XXZuufPk9+2swMSWyZnrBpRGHXw1qxGTgCNtPcFXwn8dU="
  secret_access_key: 
    secure: "RTggxJzC/xa3iIiANKsdXgp2J4tmsjcP5KD0vCokatWPYlSLD5wobrOk6u/lNQEy9ARNtYOstynRXVyhV+/0gw5i8f/6dF1xPmY6UU0Pu5VtPUXk6YpCdbcVuUuzACE4vJ3fCXrSl2F8kl/aMmId2sKEEaiHobGlf36bQDQPw93fZdY8s52oxpRvYq4T/ziMPKYS+JvfzP2SeVD3/KYa+nIgwrYAzRDse2uCpnY4C3tFysYLmbFvndV6X+KDlh0X+tK+aTYNAo3bMQXG6pP93myX4RXzdXatKSaq7pVWMDEDZlU7hgFpSrH90fir4oBQhvCub1cTli7GG1lw7OIwyqc3aIahqxIzaxYHsnA4V5VxR7P+tMiUUAU8fN+VPe6Npq1XgqF3fAcTkkObSoH80I/3q0UViro/lrw7P7/zFp2k3/+7Lh0xPVajAwGCvvuJqjFJEA2Rb8xPRXWM0PbOOpP2KE1e/BvxBu32RWJ3QvYIeysIwmrtsWSZpfK1IwXwXSgUBFumZCapx3hA9deHruT4BDn8/DJCGGCWVeiZoWrGUFxQI2F/Ng3qyUFttTrRzLiKimQiwU/a6BYvDrGq7Y0ThtiVgLyCxmjTIVIANJw80Tjxs+Yhkxo4M2Af7mKtxXmDRBR+KOPYdCYT/mDPzRkm1meNILTp4rKgdK0RoZA="
  application: ResumeApplication
  region: us-east-1d
  
  
  
