dist: trusty
sudo: required

language: node_js
node_js:
  - "stable"
addons:
  sonarcloud:
    organization: "tanujamedisetti87-github"
    token:
      secure: "c31adcd738465686855224f7f9b30c8ec5008271"
  sauce_connect:
    username: "TanujaMedisetti87"
    access_key: "130dda79-1dea-45cd-849c-24cfbe048884"
    
script:
  - sonar-scanner
  
deploy:
  - provider: codedeploy
    access_key_id: AKIAJFDSOXV523PSGZXQ
    secret_access_key: "V2a1o0/kHDyNVRS6ca2ozCOdM1BxISt+7vFyOqPPXi1es0/hTEhY4ziY8CWWBosTrrkcMl2AS0taHITf+PZ8ffC/i6EIhNmzgGPaNwBB2yRLsxDQ+OOnzZG3DKJxUszwjhOUqDkPj2qS2LACTpQc4dKixJxU5In2WuupLEoYoNaqqNRm170Az1Lzme/YN+MN2yOV2D8CNlIzdO89alod4llbPX2IscXjUyxz1cXypVckxNwjMaHWbl0GqCJilJ/jSxgyxkNjNy5pMM/+uRbvv6PCqjj8ARZC+RlSBgrc06qXVtbq3NvN7WGVuusTUydsvAxf899GZ9wpIwD35iR7f41nBTlPK4TmEAGTiVdbXMlygb4wkAE3bKqOEMVD8myAUzz60K+KkmEcrGsgXa1ZJJTXJUyJQOwvIMi59jhbf66i17qoUbMLvBQTzNDvxenxt3QjQoNHR0TaGvSxuDiizekmFe9Vq/4NxbmZRHyLxC1bQuKzoYw3O70TM3fF9Y2tMicbLO1Qr1lynYiVgtSo57DPOV+0WkiYS5GzoDzklX/VgkGWee9aj8g5LHIYSNfamZwgUtCENn0OQo62sej+PTgLipPKmRxTnCSMVXLb5Ge7IQ2oNLnyyhNGqP1JATWLX53mu97EHz6JbUWGxjOCqrQVl6mdlBHgrkwqb/h16nM="
    application: Resume
    deployment_group: ResumeGroup
    
    
    
    
    
    
    
    
    
    
    
