version: 0.0
os: linux
files:
  - source: /resume/views/index.html
    destination: /home/ec2-user
    
hooks:
  BeforeInstall:
    - location: npm-install.sh
      runas: root
      timeout: 300
  AfterInstall:
    - location: npm-start.sh
      runas: root
      timeout: 300
