version: 0.0
os: linux
files:
  - source: resume/views/index.html
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: npm-install.sh
      runas: root
  AfterInstall:
    - location: npm-start.sh
      runas: root
      timeout: 300
